---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: rihab96
    password: docker2022
- name: Push to docker hub
  docker_image:
    name: lcangular
    repository: rihab96/lcproject
    tag: latest
    source: local
    push: yes
