---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: marwenguesmi
    password: Karawannimarwen1993
- name: Push to docker hub
  docker_image:
    name: lcangular
    repository: marwenguesmi/lcproject
    tag: latest
    source: local
    push: yes
